#!/bin/bash

# please ensure your correct image path

python infer.py -c jshdr -i ./data/test/14096_A.png
python infer.py -c jshdr -i ./data/test/14786_A.png
python infer.py -c jshdr -i ./data/test/14517_A.png
python infer.py -c jshdr -i ./data/test/14336_A.png
python infer.py -c jshdr -i ./data/test/14836_A.png
python infer.py -c jshdr -i ./data/test/14119_A.png
python infer.py -c jshdr -i ./data/test/14824_A.png
python infer.py -c jshdr -i ./data/test/14884_A.png
python infer.py -c jshdr -i ./data/test/14713_A.png
python infer.py -c jshdr -i ./data/test/14594_A.png
python infer.py -c jshdr -i ./data/test/14530_A.png
python infer.py -c jshdr -i ./data/test/14240_A.png
python infer.py -c jshdr -i ./data/test/14408_A.png
python infer.py -c jshdr -i ./data/test/14160_A.png
python infer.py -c jshdr -i ./data/test/14060_A.png
python infer.py -c jshdr -i ./data/test/14050_A.png
python infer.py -c jshdr -i ./data/test/14022_A.png
python infer.py -c jshdr -i ./data/test/14399_A.png
python infer.py -c jshdr -i ./data/test/14121_A.png
python infer.py -c jshdr -i ./data/test/14840_A.png
python infer.py -c jshdr -i ./data/test/14647_A.png
python infer.py -c jshdr -i ./data/test/14567_A.png
python infer.py -c jshdr -i ./data/test/14863_A.png
python infer.py -c jshdr -i ./data/test/14417_A.png
python infer.py -c jshdr -i ./data/test/14492_A.png
python infer.py -c jshdr -i ./data/test/14666_A.png
python infer.py -c jshdr -i ./data/test/14495_A.png
python infer.py -c jshdr -i ./data/test/14249_A.png
python infer.py -c jshdr -i ./data/test/14937_A.png
python infer.py -c jshdr -i ./data/test/14982_A.png
python infer.py -c jshdr -i ./data/test/14779_A.png
python infer.py -c jshdr -i ./data/test/14107_A.png
python infer.py -c jshdr -i ./data/test/14852_A.png
python infer.py -c jshdr -i ./data/test/14206_A.png
python infer.py -c jshdr -i ./data/test/14586_A.png
python infer.py -c jshdr -i ./data/test/14152_A.png
python infer.py -c jshdr -i ./data/test/14910_A.png
python infer.py -c jshdr -i ./data/test/14488_A.png
python infer.py -c jshdr -i ./data/test/14688_A.png
python infer.py -c jshdr -i ./data/test/14797_A.png
python infer.py -c jshdr -i ./data/test/14717_A.png
python infer.py -c jshdr -i ./data/test/14013_A.png
python infer.py -c jshdr -i ./data/test/14089_A.png
python infer.py -c jshdr -i ./data/test/14460_A.png
python infer.py -c jshdr -i ./data/test/14660_A.png
python infer.py -c jshdr -i ./data/test/14444_A.png
python infer.py -c jshdr -i ./data/test/14188_A.png
python infer.py -c jshdr -i ./data/test/14359_A.png
python infer.py -c jshdr -i ./data/test/14081_A.png
python infer.py -c jshdr -i ./data/test/14709_A.png
python infer.py -c jshdr -i ./data/test/14558_A.png
python infer.py -c jshdr -i ./data/test/14516_A.png
python infer.py -c jshdr -i ./data/test/14433_A.png
python infer.py -c jshdr -i ./data/test/14979_A.png
python infer.py -c jshdr -i ./data/test/14719_A.png
python infer.py -c jshdr -i ./data/test/14701_A.png
python infer.py -c jshdr -i ./data/test/14929_A.png
python infer.py -c jshdr -i ./data/test/14680_A.png
python infer.py -c jshdr -i ./data/test/14317_A.png
python infer.py -c jshdr -i ./data/test/14706_A.png
python infer.py -c jshdr -i ./data/test/14410_A.png
python infer.py -c jshdr -i ./data/test/14216_A.png
python infer.py -c jshdr -i ./data/test/14887_A.png
python infer.py -c jshdr -i ./data/test/14080_A.png
python infer.py -c jshdr -i ./data/test/14608_A.png
python infer.py -c jshdr -i ./data/test/14113_A.png
python infer.py -c jshdr -i ./data/test/14217_A.png
python infer.py -c jshdr -i ./data/test/14769_A.png
python infer.py -c jshdr -i ./data/test/14716_A.png
python infer.py -c jshdr -i ./data/test/14684_A.png
python infer.py -c jshdr -i ./data/test/14150_A.png
python infer.py -c jshdr -i ./data/test/14454_A.png
python infer.py -c jshdr -i ./data/test/14933_A.png
python infer.py -c jshdr -i ./data/test/14429_A.png
python infer.py -c jshdr -i ./data/test/14376_A.png
python infer.py -c jshdr -i ./data/test/14546_A.png
python infer.py -c jshdr -i ./data/test/14930_A.png
python infer.py -c jshdr -i ./data/test/14439_A.png
python infer.py -c jshdr -i ./data/test/14114_A.png
python infer.py -c jshdr -i ./data/test/14169_A.png
python infer.py -c jshdr -i ./data/test/14584_A.png
python infer.py -c jshdr -i ./data/test/14618_A.png
python infer.py -c jshdr -i ./data/test/14999_A.png
python infer.py -c jshdr -i ./data/test/14531_A.png
python infer.py -c jshdr -i ./data/test/14214_A.png
python infer.py -c jshdr -i ./data/test/14034_A.png
python infer.py -c jshdr -i ./data/test/14315_A.png
python infer.py -c jshdr -i ./data/test/14021_A.png
python infer.py -c jshdr -i ./data/test/14493_A.png
python infer.py -c jshdr -i ./data/test/14432_A.png
python infer.py -c jshdr -i ./data/test/14351_A.png
python infer.py -c jshdr -i ./data/test/14847_A.png
python infer.py -c jshdr -i ./data/test/14918_A.png
python infer.py -c jshdr -i ./data/test/14705_A.png
python infer.py -c jshdr -i ./data/test/14373_A.png
python infer.py -c jshdr -i ./data/test/14934_A.png
python infer.py -c jshdr -i ./data/test/14090_A.png
python infer.py -c jshdr -i ./data/test/14231_A.png
python infer.py -c jshdr -i ./data/test/14504_A.png
python infer.py -c jshdr -i ./data/test/14735_A.png
python infer.py -c jshdr -i ./data/test/14120_A.png
python infer.py -c jshdr -i ./data/test/14860_A.png
python infer.py -c jshdr -i ./data/test/14634_A.png
python infer.py -c jshdr -i ./data/test/14112_A.png
python infer.py -c jshdr -i ./data/test/14585_A.png
python infer.py -c jshdr -i ./data/test/14385_A.png
python infer.py -c jshdr -i ./data/test/14917_A.png
python infer.py -c jshdr -i ./data/test/14230_A.png
python infer.py -c jshdr -i ./data/test/14464_A.png
python infer.py -c jshdr -i ./data/test/14803_A.png
python infer.py -c jshdr -i ./data/test/14453_A.png
python infer.py -c jshdr -i ./data/test/14238_A.png
python infer.py -c jshdr -i ./data/test/14058_A.png
python infer.py -c jshdr -i ./data/test/14153_A.png
python infer.py -c jshdr -i ./data/test/14472_A.png
python infer.py -c jshdr -i ./data/test/14406_A.png
python infer.py -c jshdr -i ./data/test/14572_A.png
python infer.py -c jshdr -i ./data/test/14017_A.png
python infer.py -c jshdr -i ./data/test/14583_A.png
python infer.py -c jshdr -i ./data/test/14566_A.png
python infer.py -c jshdr -i ./data/test/14261_A.png
python infer.py -c jshdr -i ./data/test/14850_A.png
python infer.py -c jshdr -i ./data/test/14808_A.png
python infer.py -c jshdr -i ./data/test/14582_A.png
python infer.py -c jshdr -i ./data/test/14158_A.png
python infer.py -c jshdr -i ./data/test/14144_A.png
python infer.py -c jshdr -i ./data/test/14335_A.png
python infer.py -c jshdr -i ./data/test/14712_A.png
python infer.py -c jshdr -i ./data/test/14722_A.png
python infer.py -c jshdr -i ./data/test/14483_A.png
python infer.py -c jshdr -i ./data/test/14886_A.png
python infer.py -c jshdr -i ./data/test/14623_A.png
python infer.py -c jshdr -i ./data/test/14284_A.png
python infer.py -c jshdr -i ./data/test/14175_A.png
python infer.py -c jshdr -i ./data/test/14835_A.png
python infer.py -c jshdr -i ./data/test/14878_A.png
python infer.py -c jshdr -i ./data/test/14419_A.png
python infer.py -c jshdr -i ./data/test/14368_A.png
python infer.py -c jshdr -i ./data/test/14319_A.png
python infer.py -c jshdr -i ./data/test/14456_A.png
python infer.py -c jshdr -i ./data/test/14372_A.png
python infer.py -c jshdr -i ./data/test/14131_A.png
python infer.py -c jshdr -i ./data/test/14435_A.png
python infer.py -c jshdr -i ./data/test/14445_A.png
python infer.py -c jshdr -i ./data/test/14125_A.png
python infer.py -c jshdr -i ./data/test/14632_A.png
python infer.py -c jshdr -i ./data/test/14252_A.png
python infer.py -c jshdr -i ./data/test/14568_A.png
python infer.py -c jshdr -i ./data/test/14880_A.png
python infer.py -c jshdr -i ./data/test/14294_A.png
python infer.py -c jshdr -i ./data/test/14049_A.png
python infer.py -c jshdr -i ./data/test/14543_A.png
python infer.py -c jshdr -i ./data/test/14035_A.png
python infer.py -c jshdr -i ./data/test/14613_A.png
python infer.py -c jshdr -i ./data/test/14394_A.png
python infer.py -c jshdr -i ./data/test/14141_A.png
python infer.py -c jshdr -i ./data/test/14076_A.png
python infer.py -c jshdr -i ./data/test/14147_A.png
python infer.py -c jshdr -i ./data/test/14771_A.png
python infer.py -c jshdr -i ./data/test/14415_A.png
python infer.py -c jshdr -i ./data/test/14958_A.png
python infer.py -c jshdr -i ./data/test/14612_A.png
python infer.py -c jshdr -i ./data/test/14746_A.png
python infer.py -c jshdr -i ./data/test/14498_A.png
python infer.py -c jshdr -i ./data/test/14668_A.png
python infer.py -c jshdr -i ./data/test/14086_A.png
python infer.py -c jshdr -i ./data/test/14396_A.png
python infer.py -c jshdr -i ./data/test/14070_A.png
python infer.py -c jshdr -i ./data/test/14302_A.png
python infer.py -c jshdr -i ./data/test/14811_A.png
python infer.py -c jshdr -i ./data/test/14053_A.png
python infer.py -c jshdr -i ./data/test/14787_A.png
python infer.py -c jshdr -i ./data/test/14995_A.png
python infer.py -c jshdr -i ./data/test/14509_A.png
python infer.py -c jshdr -i ./data/test/14476_A.png
python infer.py -c jshdr -i ./data/test/14222_A.png
python infer.py -c jshdr -i ./data/test/14030_A.png
python infer.py -c jshdr -i ./data/test/14469_A.png
python infer.py -c jshdr -i ./data/test/14539_A.png
python infer.py -c jshdr -i ./data/test/14280_A.png
python infer.py -c jshdr -i ./data/test/14777_A.png
python infer.py -c jshdr -i ./data/test/14156_A.png
python infer.py -c jshdr -i ./data/test/14671_A.png
python infer.py -c jshdr -i ./data/test/14755_A.png
python infer.py -c jshdr -i ./data/test/14978_A.png
python infer.py -c jshdr -i ./data/test/14094_A.png
python infer.py -c jshdr -i ./data/test/14865_A.png
python infer.py -c jshdr -i ./data/test/14649_A.png
python infer.py -c jshdr -i ./data/test/14973_A.png
python infer.py -c jshdr -i ./data/test/14014_A.png
python infer.py -c jshdr -i ./data/test/14550_A.png
python infer.py -c jshdr -i ./data/test/14339_A.png
python infer.py -c jshdr -i ./data/test/14437_A.png
python infer.py -c jshdr -i ./data/test/14513_A.png
python infer.py -c jshdr -i ./data/test/14648_A.png
python infer.py -c jshdr -i ./data/test/14272_A.png
python infer.py -c jshdr -i ./data/test/14481_A.png
python infer.py -c jshdr -i ./data/test/14625_A.png
python infer.py -c jshdr -i ./data/test/14063_A.png
python infer.py -c jshdr -i ./data/test/14799_A.png
python infer.py -c jshdr -i ./data/test/14245_A.png
python infer.py -c jshdr -i ./data/test/14526_A.png
python infer.py -c jshdr -i ./data/test/14588_A.png
python infer.py -c jshdr -i ./data/test/14800_A.png
python infer.py -c jshdr -i ./data/test/14924_A.png
python infer.py -c jshdr -i ./data/test/14229_A.png
python infer.py -c jshdr -i ./data/test/14382_A.png
python infer.py -c jshdr -i ./data/test/14077_A.png
python infer.py -c jshdr -i ./data/test/14670_A.png
python infer.py -c jshdr -i ./data/test/14548_A.png
python infer.py -c jshdr -i ./data/test/14004_A.png
python infer.py -c jshdr -i ./data/test/14146_A.png
python infer.py -c jshdr -i ./data/test/14383_A.png
python infer.py -c jshdr -i ./data/test/14418_A.png
python infer.py -c jshdr -i ./data/test/14964_A.png
python infer.py -c jshdr -i ./data/test/14037_A.png
python infer.py -c jshdr -i ./data/test/14616_A.png
python infer.py -c jshdr -i ./data/test/14673_A.png
python infer.py -c jshdr -i ./data/test/14132_A.png
python infer.py -c jshdr -i ./data/test/14292_A.png
python infer.py -c jshdr -i ./data/test/14602_A.png
python infer.py -c jshdr -i ./data/test/14796_A.png
python infer.py -c jshdr -i ./data/test/14675_A.png
python infer.py -c jshdr -i ./data/test/14812_A.png
python infer.py -c jshdr -i ./data/test/15000_A.png
python infer.py -c jshdr -i ./data/test/14026_A.png
python infer.py -c jshdr -i ./data/test/14593_A.png
python infer.py -c jshdr -i ./data/test/14213_A.png
python infer.py -c jshdr -i ./data/test/14977_A.png
python infer.py -c jshdr -i ./data/test/14042_A.png
python infer.py -c jshdr -i ./data/test/14774_A.png
python infer.py -c jshdr -i ./data/test/14992_A.png
python infer.py -c jshdr -i ./data/test/14685_A.png
python infer.py -c jshdr -i ./data/test/14815_A.png
python infer.py -c jshdr -i ./data/test/14867_A.png
python infer.py -c jshdr -i ./data/test/14420_A.png
python infer.py -c jshdr -i ./data/test/14872_A.png
python infer.py -c jshdr -i ./data/test/14434_A.png
python infer.py -c jshdr -i ./data/test/14921_A.png
python infer.py -c jshdr -i ./data/test/14167_A.png
python infer.py -c jshdr -i ./data/test/14008_A.png
python infer.py -c jshdr -i ./data/test/14387_A.png
python infer.py -c jshdr -i ./data/test/14040_A.png
python infer.py -c jshdr -i ./data/test/14327_A.png
python infer.py -c jshdr -i ./data/test/14674_A.png
python infer.py -c jshdr -i ./data/test/14375_A.png
python infer.py -c jshdr -i ./data/test/14003_A.png
python infer.py -c jshdr -i ./data/test/14316_A.png
python infer.py -c jshdr -i ./data/test/14243_A.png
python infer.py -c jshdr -i ./data/test/14091_A.png
python infer.py -c jshdr -i ./data/test/14337_A.png
python infer.py -c jshdr -i ./data/test/14678_A.png
python infer.py -c jshdr -i ./data/test/14848_A.png
python infer.py -c jshdr -i ./data/test/14027_A.png
python infer.py -c jshdr -i ./data/test/14257_A.png
python infer.py -c jshdr -i ./data/test/14524_A.png
python infer.py -c jshdr -i ./data/test/14145_A.png
python infer.py -c jshdr -i ./data/test/14179_A.png
python infer.py -c jshdr -i ./data/test/14260_A.png
python infer.py -c jshdr -i ./data/test/14851_A.png
python infer.py -c jshdr -i ./data/test/14443_A.png
python infer.py -c jshdr -i ./data/test/14378_A.png
python infer.py -c jshdr -i ./data/test/14587_A.png
python infer.py -c jshdr -i ./data/test/14573_A.png
python infer.py -c jshdr -i ./data/test/14102_A.png
python infer.py -c jshdr -i ./data/test/14826_A.png
python infer.py -c jshdr -i ./data/test/14170_A.png
python infer.py -c jshdr -i ./data/test/14110_A.png
python infer.py -c jshdr -i ./data/test/14190_A.png
python infer.py -c jshdr -i ./data/test/14519_A.png
python infer.py -c jshdr -i ./data/test/14422_A.png
python infer.py -c jshdr -i ./data/test/14215_A.png
python infer.py -c jshdr -i ./data/test/14099_A.png
python infer.py -c jshdr -i ./data/test/14900_A.png
python infer.py -c jshdr -i ./data/test/14301_A.png
python infer.py -c jshdr -i ./data/test/14565_A.png
python infer.py -c jshdr -i ./data/test/14825_A.png
python infer.py -c jshdr -i ./data/test/14039_A.png
python infer.py -c jshdr -i ./data/test/14333_A.png
python infer.py -c jshdr -i ./data/test/14159_A.png
python infer.py -c jshdr -i ./data/test/14932_A.png
python infer.py -c jshdr -i ./data/test/14414_A.png
python infer.py -c jshdr -i ./data/test/14267_A.png
python infer.py -c jshdr -i ./data/test/14392_A.png
python infer.py -c jshdr -i ./data/test/14409_A.png
python infer.py -c jshdr -i ./data/test/14321_A.png
python infer.py -c jshdr -i ./data/test/14739_A.png
python infer.py -c jshdr -i ./data/test/14545_A.png
python infer.py -c jshdr -i ./data/test/14038_A.png
python infer.py -c jshdr -i ./data/test/14166_A.png
python infer.py -c jshdr -i ./data/test/14732_A.png
python infer.py -c jshdr -i ./data/test/14508_A.png
python infer.py -c jshdr -i ./data/test/14750_A.png
python infer.py -c jshdr -i ./data/test/14269_A.png
python infer.py -c jshdr -i ./data/test/14991_A.png
python infer.py -c jshdr -i ./data/test/14044_A.png
python infer.py -c jshdr -i ./data/test/14452_A.png
python infer.py -c jshdr -i ./data/test/14936_A.png
python infer.py -c jshdr -i ./data/test/14183_A.png
python infer.py -c jshdr -i ./data/test/14791_A.png
python infer.py -c jshdr -i ./data/test/14364_A.png
python infer.py -c jshdr -i ./data/test/14061_A.png
python infer.py -c jshdr -i ./data/test/14505_A.png
python infer.py -c jshdr -i ./data/test/14534_A.png
python infer.py -c jshdr -i ./data/test/14427_A.png
python infer.py -c jshdr -i ./data/test/14283_A.png
python infer.py -c jshdr -i ./data/test/14191_A.png
python infer.py -c jshdr -i ./data/test/14990_A.png
python infer.py -c jshdr -i ./data/test/14412_A.png
python infer.py -c jshdr -i ./data/test/14388_A.png
python infer.py -c jshdr -i ./data/test/14756_A.png
python infer.py -c jshdr -i ./data/test/14224_A.png
python infer.py -c jshdr -i ./data/test/14365_A.png
python infer.py -c jshdr -i ./data/test/14699_A.png
python infer.py -c jshdr -i ./data/test/14312_A.png
python infer.py -c jshdr -i ./data/test/14798_A.png
python infer.py -c jshdr -i ./data/test/14140_A.png
python infer.py -c jshdr -i ./data/test/14967_A.png
python infer.py -c jshdr -i ./data/test/14607_A.png
python infer.py -c jshdr -i ./data/test/14928_A.png
python infer.py -c jshdr -i ./data/test/14168_A.png
python infer.py -c jshdr -i ./data/test/14380_A.png
python infer.py -c jshdr -i ./data/test/14023_A.png
python infer.py -c jshdr -i ./data/test/14759_A.png
python infer.py -c jshdr -i ./data/test/14549_A.png
python infer.py -c jshdr -i ./data/test/14820_A.png
python infer.py -c jshdr -i ./data/test/14471_A.png
python infer.py -c jshdr -i ./data/test/14725_A.png
python infer.py -c jshdr -i ./data/test/14942_A.png
python infer.py -c jshdr -i ./data/test/14781_A.png
python infer.py -c jshdr -i ./data/test/14743_A.png
python infer.py -c jshdr -i ./data/test/14667_A.png
python infer.py -c jshdr -i ./data/test/14421_A.png
python infer.py -c jshdr -i ./data/test/14679_A.png
python infer.py -c jshdr -i ./data/test/14610_A.png
python infer.py -c jshdr -i ./data/test/14987_A.png
python infer.py -c jshdr -i ./data/test/14642_A.png
python infer.py -c jshdr -i ./data/test/14201_A.png
python infer.py -c jshdr -i ./data/test/14205_A.png
python infer.py -c jshdr -i ./data/test/14029_A.png
python infer.py -c jshdr -i ./data/test/14497_A.png
python infer.py -c jshdr -i ./data/test/14221_A.png
python infer.py -c jshdr -i ./data/test/14861_A.png
python infer.py -c jshdr -i ./data/test/14544_A.png
python infer.py -c jshdr -i ./data/test/14055_A.png
python infer.py -c jshdr -i ./data/test/14833_A.png
python infer.py -c jshdr -i ./data/test/14662_A.png
python infer.py -c jshdr -i ./data/test/14025_A.png
python infer.py -c jshdr -i ./data/test/14974_A.png
python infer.py -c jshdr -i ./data/test/14574_A.png
python infer.py -c jshdr -i ./data/test/14912_A.png
python infer.py -c jshdr -i ./data/test/14537_A.png
python infer.py -c jshdr -i ./data/test/14466_A.png
python infer.py -c jshdr -i ./data/test/14694_A.png
python infer.py -c jshdr -i ./data/test/14527_A.png
python infer.py -c jshdr -i ./data/test/14129_A.png
python infer.py -c jshdr -i ./data/test/14304_A.png
python infer.py -c jshdr -i ./data/test/14968_A.png
python infer.py -c jshdr -i ./data/test/14561_A.png
python infer.py -c jshdr -i ./data/test/14377_A.png
python infer.py -c jshdr -i ./data/test/14597_A.png
python infer.py -c jshdr -i ./data/test/14281_A.png
python infer.py -c jshdr -i ./data/test/14785_A.png
python infer.py -c jshdr -i ./data/test/14291_A.png
python infer.py -c jshdr -i ./data/test/14753_A.png
python infer.py -c jshdr -i ./data/test/14071_A.png
python infer.py -c jshdr -i ./data/test/14818_A.png
python infer.py -c jshdr -i ./data/test/14174_A.png
python infer.py -c jshdr -i ./data/test/14328_A.png
python infer.py -c jshdr -i ./data/test/14938_A.png
python infer.py -c jshdr -i ./data/test/14986_A.png
python infer.py -c jshdr -i ./data/test/14983_A.png
python infer.py -c jshdr -i ./data/test/14054_A.png
python infer.py -c jshdr -i ./data/test/14700_A.png
python infer.py -c jshdr -i ./data/test/14208_A.png
python infer.py -c jshdr -i ./data/test/14024_A.png
python infer.py -c jshdr -i ./data/test/14726_A.png
python infer.py -c jshdr -i ./data/test/14031_A.png
python infer.py -c jshdr -i ./data/test/14552_A.png
python infer.py -c jshdr -i ./data/test/14438_A.png
python infer.py -c jshdr -i ./data/test/14484_A.png
python infer.py -c jshdr -i ./data/test/14734_A.png
python infer.py -c jshdr -i ./data/test/14661_A.png
python infer.py -c jshdr -i ./data/test/14883_A.png
python infer.py -c jshdr -i ./data/test/14093_A.png
python infer.py -c jshdr -i ./data/test/14455_A.png
python infer.py -c jshdr -i ./data/test/14871_A.png
python infer.py -c jshdr -i ./data/test/14381_A.png
python infer.py -c jshdr -i ./data/test/14277_A.png
python infer.py -c jshdr -i ./data/test/14097_A.png
python infer.py -c jshdr -i ./data/test/14361_A.png
python infer.py -c jshdr -i ./data/test/14300_A.png
python infer.py -c jshdr -i ./data/test/14181_A.png
python infer.py -c jshdr -i ./data/test/14232_A.png
python infer.py -c jshdr -i ./data/test/14347_A.png
python infer.py -c jshdr -i ./data/test/14157_A.png
python infer.py -c jshdr -i ./data/test/14614_A.png
python infer.py -c jshdr -i ./data/test/14819_A.png
python infer.py -c jshdr -i ./data/test/14748_A.png
python infer.py -c jshdr -i ./data/test/14894_A.png
python infer.py -c jshdr -i ./data/test/14589_A.png
python infer.py -c jshdr -i ./data/test/14931_A.png
python infer.py -c jshdr -i ./data/test/14098_A.png
python infer.py -c jshdr -i ./data/test/14611_A.png
python infer.py -c jshdr -i ./data/test/14207_A.png
python infer.py -c jshdr -i ./data/test/14329_A.png
python infer.py -c jshdr -i ./data/test/14940_A.png
python infer.py -c jshdr -i ./data/test/14348_A.png
python infer.py -c jshdr -i ./data/test/14202_A.png
python infer.py -c jshdr -i ./data/test/14354_A.png
python infer.py -c jshdr -i ./data/test/14617_A.png
python infer.py -c jshdr -i ./data/test/14171_A.png
python infer.py -c jshdr -i ./data/test/14130_A.png
python infer.py -c jshdr -i ./data/test/14845_A.png
python infer.py -c jshdr -i ./data/test/14782_A.png
python infer.py -c jshdr -i ./data/test/14124_A.png
python infer.py -c jshdr -i ./data/test/14203_A.png
python infer.py -c jshdr -i ./data/test/14627_A.png
python infer.py -c jshdr -i ./data/test/14875_A.png
python infer.py -c jshdr -i ./data/test/14411_A.png
python infer.py -c jshdr -i ./data/test/14447_A.png
python infer.py -c jshdr -i ./data/test/14813_A.png
python infer.py -c jshdr -i ./data/test/14177_A.png
python infer.py -c jshdr -i ./data/test/14463_A.png
python infer.py -c jshdr -i ./data/test/14736_A.png
python infer.py -c jshdr -i ./data/test/14404_A.png
python infer.py -c jshdr -i ./data/test/14109_A.png
python infer.py -c jshdr -i ./data/test/14256_A.png
python infer.py -c jshdr -i ./data/test/14948_A.png
python infer.py -c jshdr -i ./data/test/14305_A.png
python infer.py -c jshdr -i ./data/test/14136_A.png
python infer.py -c jshdr -i ./data/test/14154_A.png
python infer.py -c jshdr -i ./data/test/14559_A.png
python infer.py -c jshdr -i ./data/test/14436_A.png
python infer.py -c jshdr -i ./data/test/14862_A.png
python infer.py -c jshdr -i ./data/test/14162_A.png
python infer.py -c jshdr -i ./data/test/14644_A.png
python infer.py -c jshdr -i ./data/test/14068_A.png
python infer.py -c jshdr -i ./data/test/14323_A.png
python infer.py -c jshdr -i ./data/test/14817_A.png
python infer.py -c jshdr -i ./data/test/14757_A.png
python infer.py -c jshdr -i ./data/test/14638_A.png
python infer.py -c jshdr -i ./data/test/14111_A.png
python infer.py -c jshdr -i ./data/test/14892_A.png
python infer.py -c jshdr -i ./data/test/14320_A.png
python infer.py -c jshdr -i ./data/test/14650_A.png
python infer.py -c jshdr -i ./data/test/14542_A.png
python infer.py -c jshdr -i ./data/test/14898_A.png
python infer.py -c jshdr -i ./data/test/14806_A.png
python infer.py -c jshdr -i ./data/test/14046_A.png
python infer.py -c jshdr -i ./data/test/14180_A.png
python infer.py -c jshdr -i ./data/test/14490_A.png
python infer.py -c jshdr -i ./data/test/14311_A.png
python infer.py -c jshdr -i ./data/test/14106_A.png
python infer.py -c jshdr -i ./data/test/14103_A.png
python infer.py -c jshdr -i ./data/test/14244_A.png
python infer.py -c jshdr -i ./data/test/14927_A.png
python infer.py -c jshdr -i ./data/test/14723_A.png
python infer.py -c jshdr -i ./data/test/14707_A.png
python infer.py -c jshdr -i ./data/test/14187_A.png
python infer.py -c jshdr -i ./data/test/14631_A.png
python infer.py -c jshdr -i ./data/test/14345_A.png
python infer.py -c jshdr -i ./data/test/14869_A.png
python infer.py -c jshdr -i ./data/test/14235_A.png
python infer.py -c jshdr -i ./data/test/14624_A.png
python infer.py -c jshdr -i ./data/test/14809_A.png
python infer.py -c jshdr -i ./data/test/14993_A.png
python infer.py -c jshdr -i ./data/test/14366_A.png
python infer.py -c jshdr -i ./data/test/14010_A.png
python infer.py -c jshdr -i ./data/test/14630_A.png
python infer.py -c jshdr -i ./data/test/14965_A.png
python infer.py -c jshdr -i ./data/test/14962_A.png
python infer.py -c jshdr -i ./data/test/14289_A.png
python infer.py -c jshdr -i ./data/test/14966_A.png
python infer.py -c jshdr -i ./data/test/14350_A.png
python infer.py -c jshdr -i ./data/test/14913_A.png
python infer.py -c jshdr -i ./data/test/14902_A.png
python infer.py -c jshdr -i ./data/test/14309_A.png
python infer.py -c jshdr -i ./data/test/14541_A.png
python infer.py -c jshdr -i ./data/test/14639_A.png
python infer.py -c jshdr -i ./data/test/14874_A.png
python infer.py -c jshdr -i ./data/test/14687_A.png
python infer.py -c jshdr -i ./data/test/14115_A.png
python infer.py -c jshdr -i ./data/test/14873_A.png
python infer.py -c jshdr -i ./data/test/14721_A.png
python infer.py -c jshdr -i ./data/test/14959_A.png
python infer.py -c jshdr -i ./data/test/14143_A.png
python infer.py -c jshdr -i ./data/test/14133_A.png
python infer.py -c jshdr -i ./data/test/14370_A.png
python infer.py -c jshdr -i ./data/test/14784_A.png
python infer.py -c jshdr -i ./data/test/14468_A.png
python infer.py -c jshdr -i ./data/test/14676_A.png
python infer.py -c jshdr -i ./data/test/14379_A.png
python infer.py -c jshdr -i ./data/test/14760_A.png
python infer.py -c jshdr -i ./data/test/14264_A.png
python infer.py -c jshdr -i ./data/test/14075_A.png
python infer.py -c jshdr -i ./data/test/14939_A.png
python infer.py -c jshdr -i ./data/test/14578_A.png
python infer.py -c jshdr -i ./data/test/14395_A.png
python infer.py -c jshdr -i ./data/test/14403_A.png
python infer.py -c jshdr -i ./data/test/14138_A.png
python infer.py -c jshdr -i ./data/test/14259_A.png
python infer.py -c jshdr -i ./data/test/14609_A.png
python infer.py -c jshdr -i ./data/test/14033_A.png
python infer.py -c jshdr -i ./data/test/14752_A.png
python infer.py -c jshdr -i ./data/test/14570_A.png
python infer.py -c jshdr -i ./data/test/14816_A.png
python infer.py -c jshdr -i ./data/test/14814_A.png
python infer.py -c jshdr -i ./data/test/14108_A.png
python infer.py -c jshdr -i ./data/test/14714_A.png
python infer.py -c jshdr -i ./data/test/14265_A.png
python infer.py -c jshdr -i ./data/test/14314_A.png
python infer.py -c jshdr -i ./data/test/14349_A.png
python infer.py -c jshdr -i ./data/test/14615_A.png
python infer.py -c jshdr -i ./data/test/14052_A.png
python infer.py -c jshdr -i ./data/test/14295_A.png
python infer.py -c jshdr -i ./data/test/14001_A.png
python infer.py -c jshdr -i ./data/test/14340_A.png
python infer.py -c jshdr -i ./data/test/14686_A.png
python infer.py -c jshdr -i ./data/test/14864_A.png
python infer.py -c jshdr -i ./data/test/14903_A.png
python infer.py -c jshdr -i ./data/test/14946_A.png
python infer.py -c jshdr -i ./data/test/14830_A.png
python infer.py -c jshdr -i ./data/test/14839_A.png
python infer.py -c jshdr -i ./data/test/14961_A.png
python infer.py -c jshdr -i ./data/test/14853_A.png
python infer.py -c jshdr -i ./data/test/14346_A.png
python infer.py -c jshdr -i ./data/test/14290_A.png
python infer.py -c jshdr -i ./data/test/14606_A.png
python infer.py -c jshdr -i ./data/test/14621_A.png
python infer.py -c jshdr -i ./data/test/14945_A.png
python infer.py -c jshdr -i ./data/test/14740_A.png
python infer.py -c jshdr -i ./data/test/14947_A.png
python infer.py -c jshdr -i ./data/test/14604_A.png
python infer.py -c jshdr -i ./data/test/14528_A.png
python infer.py -c jshdr -i ./data/test/14553_A.png
python infer.py -c jshdr -i ./data/test/14116_A.png
python infer.py -c jshdr -i ./data/test/14592_A.png
python infer.py -c jshdr -i ./data/test/14935_A.png
python infer.py -c jshdr -i ./data/test/14478_A.png
python infer.py -c jshdr -i ./data/test/14219_A.png
python infer.py -c jshdr -i ./data/test/14384_A.png
python infer.py -c jshdr -i ./data/test/14577_A.png
python infer.py -c jshdr -i ./data/test/14459_A.png
python infer.py -c jshdr -i ./data/test/14262_A.png
python infer.py -c jshdr -i ./data/test/14251_A.png
python infer.py -c jshdr -i ./data/test/14338_A.png
python infer.py -c jshdr -i ./data/test/14728_A.png
python infer.py -c jshdr -i ./data/test/14360_A.png
python infer.py -c jshdr -i ./data/test/14695_A.png
python infer.py -c jshdr -i ./data/test/14185_A.png
python infer.py -c jshdr -i ./data/test/14367_A.png
python infer.py -c jshdr -i ./data/test/14876_A.png
python infer.py -c jshdr -i ./data/test/14870_A.png
python infer.py -c jshdr -i ./data/test/14901_A.png
python infer.py -c jshdr -i ./data/test/14428_A.png
python infer.py -c jshdr -i ./data/test/14100_A.png
python infer.py -c jshdr -i ./data/test/14888_A.png
python infer.py -c jshdr -i ./data/test/14765_A.png
python infer.py -c jshdr -i ./data/test/14253_A.png
python infer.py -c jshdr -i ./data/test/14652_A.png
python infer.py -c jshdr -i ./data/test/14654_A.png
python infer.py -c jshdr -i ./data/test/14424_A.png
python infer.py -c jshdr -i ./data/test/14073_A.png
python infer.py -c jshdr -i ./data/test/14523_A.png
python infer.py -c jshdr -i ./data/test/14804_A.png
python infer.py -c jshdr -i ./data/test/14605_A.png
python infer.py -c jshdr -i ./data/test/14430_A.png
python infer.py -c jshdr -i ./data/test/14951_A.png
python infer.py -c jshdr -i ./data/test/14088_A.png
python infer.py -c jshdr -i ./data/test/14683_A.png
python infer.py -c jshdr -i ./data/test/14494_A.png
python infer.py -c jshdr -i ./data/test/14234_A.png
python infer.py -c jshdr -i ./data/test/14225_A.png
python infer.py -c jshdr -i ./data/test/14941_A.png
python infer.py -c jshdr -i ./data/test/14554_A.png
python infer.py -c jshdr -i ./data/test/14475_A.png
python infer.py -c jshdr -i ./data/test/14598_A.png
python infer.py -c jshdr -i ./data/test/14984_A.png
python infer.py -c jshdr -i ./data/test/14282_A.png
python infer.py -c jshdr -i ./data/test/14754_A.png
python infer.py -c jshdr -i ./data/test/14792_A.png
python infer.py -c jshdr -i ./data/test/14479_A.png
python infer.py -c jshdr -i ./data/test/14095_A.png
python infer.py -c jshdr -i ./data/test/14596_A.png
python infer.py -c jshdr -i ./data/test/14563_A.png
python infer.py -c jshdr -i ./data/test/14768_A.png
python infer.py -c jshdr -i ./data/test/14450_A.png
python infer.py -c jshdr -i ./data/test/14250_A.png
python infer.py -c jshdr -i ./data/test/14330_A.png
python infer.py -c jshdr -i ./data/test/14952_A.png
python infer.py -c jshdr -i ./data/test/14477_A.png
python infer.py -c jshdr -i ./data/test/14332_A.png
python infer.py -c jshdr -i ./data/test/14389_A.png
python infer.py -c jshdr -i ./data/test/14356_A.png
python infer.py -c jshdr -i ./data/test/14770_A.png
python infer.py -c jshdr -i ./data/test/14522_A.png
python infer.py -c jshdr -i ./data/test/14212_A.png
python infer.py -c jshdr -i ./data/test/14727_A.png
python infer.py -c jshdr -i ./data/test/14511_A.png
python infer.py -c jshdr -i ./data/test/14226_A.png
python infer.py -c jshdr -i ./data/test/14331_A.png
python infer.py -c jshdr -i ./data/test/14318_A.png
python infer.py -c jshdr -i ./data/test/14241_A.png
python infer.py -c jshdr -i ./data/test/14926_A.png
python infer.py -c jshdr -i ./data/test/14064_A.png
python infer.py -c jshdr -i ./data/test/14148_A.png
python infer.py -c jshdr -i ./data/test/14390_A.png
python infer.py -c jshdr -i ./data/test/14622_A.png
python infer.py -c jshdr -i ./data/test/14521_A.png
python infer.py -c jshdr -i ./data/test/14084_A.png
python infer.py -c jshdr -i ./data/test/14821_A.png
python infer.py -c jshdr -i ./data/test/14751_A.png
python infer.py -c jshdr -i ./data/test/14733_A.png
python infer.py -c jshdr -i ./data/test/14059_A.png
python infer.py -c jshdr -i ./data/test/14762_A.png
python infer.py -c jshdr -i ./data/test/14971_A.png
python infer.py -c jshdr -i ./data/test/14161_A.png
python infer.py -c jshdr -i ./data/test/14560_A.png
python infer.py -c jshdr -i ./data/test/14126_A.png
python infer.py -c jshdr -i ./data/test/14134_A.png
python infer.py -c jshdr -i ./data/test/14149_A.png
python infer.py -c jshdr -i ./data/test/14353_A.png
python infer.py -c jshdr -i ./data/test/14776_A.png
python infer.py -c jshdr -i ./data/test/14855_A.png
python infer.py -c jshdr -i ./data/test/14298_A.png
python infer.py -c jshdr -i ./data/test/14972_A.png
python infer.py -c jshdr -i ./data/test/14237_A.png
python infer.py -c jshdr -i ./data/test/14032_A.png
python infer.py -c jshdr -i ./data/test/14413_A.png
python infer.py -c jshdr -i ./data/test/14326_A.png
python infer.py -c jshdr -i ./data/test/14248_A.png
python infer.py -c jshdr -i ./data/test/14407_A.png
python infer.py -c jshdr -i ./data/test/14104_A.png
python infer.py -c jshdr -i ./data/test/14749_A.png
python infer.py -c jshdr -i ./data/test/14062_A.png
python infer.py -c jshdr -i ./data/test/14502_A.png
python infer.py -c jshdr -i ./data/test/14641_A.png
python infer.py -c jshdr -i ./data/test/14842_A.png
python infer.py -c jshdr -i ./data/test/14985_A.png
python infer.py -c jshdr -i ./data/test/14139_A.png
python infer.py -c jshdr -i ./data/test/14092_A.png
python infer.py -c jshdr -i ./data/test/14482_A.png
python infer.py -c jshdr -i ./data/test/14764_A.png
python infer.py -c jshdr -i ./data/test/14446_A.png
python infer.py -c jshdr -i ./data/test/14794_A.png
python infer.py -c jshdr -i ./data/test/14665_A.png
python infer.py -c jshdr -i ./data/test/14807_A.png
python infer.py -c jshdr -i ./data/test/14425_A.png
python infer.py -c jshdr -i ./data/test/14877_A.png
python infer.py -c jshdr -i ./data/test/14747_A.png
python infer.py -c jshdr -i ./data/test/14620_A.png
python infer.py -c jshdr -i ./data/test/14306_A.png
python infer.py -c jshdr -i ./data/test/14963_A.png
python infer.py -c jshdr -i ./data/test/14018_A.png
python infer.py -c jshdr -i ./data/test/14451_A.png
python infer.py -c jshdr -i ./data/test/14664_A.png
python infer.py -c jshdr -i ./data/test/14896_A.png
python infer.py -c jshdr -i ./data/test/14246_A.png
python infer.py -c jshdr -i ./data/test/14702_A.png
python infer.py -c jshdr -i ./data/test/14909_A.png
python infer.py -c jshdr -i ./data/test/14325_A.png
python infer.py -c jshdr -i ./data/test/14975_A.png
python infer.py -c jshdr -i ./data/test/14827_A.png
python infer.py -c jshdr -i ./data/test/14489_A.png
python infer.py -c jshdr -i ./data/test/14532_A.png
python infer.py -c jshdr -i ./data/test/14703_A.png
python infer.py -c jshdr -i ./data/test/14881_A.png
python infer.py -c jshdr -i ./data/test/14908_A.png
python infer.py -c jshdr -i ./data/test/14857_A.png
python infer.py -c jshdr -i ./data/test/14801_A.png
python infer.py -c jshdr -i ./data/test/14767_A.png
python infer.py -c jshdr -i ./data/test/14198_A.png
python infer.py -c jshdr -i ./data/test/14795_A.png
python infer.py -c jshdr -i ./data/test/14858_A.png
python infer.py -c jshdr -i ./data/test/14741_A.png
python infer.py -c jshdr -i ./data/test/14691_A.png
python infer.py -c jshdr -i ./data/test/14274_A.png
python infer.py -c jshdr -i ./data/test/14048_A.png
python infer.py -c jshdr -i ./data/test/14303_A.png
python infer.py -c jshdr -i ./data/test/14763_A.png
python infer.py -c jshdr -i ./data/test/14672_A.png
python infer.py -c jshdr -i ./data/test/14196_A.png
python infer.py -c jshdr -i ./data/test/14663_A.png
python infer.py -c jshdr -i ./data/test/14956_A.png
python infer.py -c jshdr -i ./data/test/14628_A.png
python infer.py -c jshdr -i ./data/test/14920_A.png
python infer.py -c jshdr -i ./data/test/14905_A.png
python infer.py -c jshdr -i ./data/test/14448_A.png
python infer.py -c jshdr -i ./data/test/14491_A.png
python infer.py -c jshdr -i ./data/test/14711_A.png
python infer.py -c jshdr -i ./data/test/14895_A.png
python infer.py -c jshdr -i ./data/test/14834_A.png
python infer.py -c jshdr -i ./data/test/14254_A.png
python infer.py -c jshdr -i ./data/test/14643_A.png
python infer.py -c jshdr -i ./data/test/14449_A.png
python infer.py -c jshdr -i ./data/test/14374_A.png
python infer.py -c jshdr -i ./data/test/14646_A.png
python infer.py -c jshdr -i ./data/test/14009_A.png
python infer.py -c jshdr -i ./data/test/14431_A.png
python infer.py -c jshdr -i ./data/test/14590_A.png
python infer.py -c jshdr -i ./data/test/14137_A.png
python infer.py -c jshdr -i ./data/test/14575_A.png
python infer.py -c jshdr -i ./data/test/14907_A.png
python infer.py -c jshdr -i ./data/test/14223_A.png
python infer.py -c jshdr -i ./data/test/14397_A.png
python infer.py -c jshdr -i ./data/test/14363_A.png
python infer.py -c jshdr -i ./data/test/14057_A.png
python infer.py -c jshdr -i ./data/test/14953_A.png
python infer.py -c jshdr -i ./data/test/14514_A.png
python infer.py -c jshdr -i ./data/test/14729_A.png
python infer.py -c jshdr -i ./data/test/14841_A.png
python infer.py -c jshdr -i ./data/test/14293_A.png
python infer.py -c jshdr -i ./data/test/14856_A.png
python infer.py -c jshdr -i ./data/test/14117_A.png
python infer.py -c jshdr -i ./data/test/14210_A.png
python infer.py -c jshdr -i ./data/test/14047_A.png
python infer.py -c jshdr -i ./data/test/14135_A.png
python infer.py -c jshdr -i ./data/test/14085_A.png
python infer.py -c jshdr -i ./data/test/14442_A.png
python infer.py -c jshdr -i ./data/test/14540_A.png
python infer.py -c jshdr -i ./data/test/14899_A.png
python infer.py -c jshdr -i ./data/test/14704_A.png
python infer.py -c jshdr -i ./data/test/14461_A.png
python infer.py -c jshdr -i ./data/test/14581_A.png
python infer.py -c jshdr -i ./data/test/14636_A.png
python infer.py -c jshdr -i ./data/test/14402_A.png
python infer.py -c jshdr -i ./data/test/14659_A.png
python infer.py -c jshdr -i ./data/test/14943_A.png
python infer.py -c jshdr -i ./data/test/14204_A.png
python infer.py -c jshdr -i ./data/test/14007_A.png
python infer.py -c jshdr -i ./data/test/14778_A.png
python infer.py -c jshdr -i ./data/test/14831_A.png
python infer.py -c jshdr -i ./data/test/14805_A.png
python infer.py -c jshdr -i ./data/test/14822_A.png
python infer.py -c jshdr -i ./data/test/14083_A.png
python infer.py -c jshdr -i ./data/test/14843_A.png
python infer.py -c jshdr -i ./data/test/14067_A.png
python infer.py -c jshdr -i ./data/test/14195_A.png
python infer.py -c jshdr -i ./data/test/14236_A.png
python infer.py -c jshdr -i ./data/test/14105_A.png
python infer.py -c jshdr -i ./data/test/14405_A.png
python infer.py -c jshdr -i ./data/test/14151_A.png
python infer.py -c jshdr -i ./data/test/14989_A.png
python infer.py -c jshdr -i ./data/test/14783_A.png
python infer.py -c jshdr -i ./data/test/14164_A.png
python infer.py -c jshdr -i ./data/test/14655_A.png
python infer.py -c jshdr -i ./data/test/14718_A.png
python infer.py -c jshdr -i ./data/test/14658_A.png
python infer.py -c jshdr -i ./data/test/14473_A.png
python infer.py -c jshdr -i ./data/test/14352_A.png
python infer.py -c jshdr -i ./data/test/14186_A.png
python infer.py -c jshdr -i ./data/test/14882_A.png
python infer.py -c jshdr -i ./data/test/14503_A.png
python infer.py -c jshdr -i ./data/test/14669_A.png
python infer.py -c jshdr -i ./data/test/14275_A.png
python infer.py -c jshdr -i ./data/test/14019_A.png
python infer.py -c jshdr -i ./data/test/14200_A.png
python infer.py -c jshdr -i ./data/test/14342_A.png
python infer.py -c jshdr -i ./data/test/14465_A.png
python infer.py -c jshdr -i ./data/test/14199_A.png
python infer.py -c jshdr -i ./data/test/14579_A.png
python infer.py -c jshdr -i ./data/test/14288_A.png
python infer.py -c jshdr -i ./data/test/14467_A.png
python infer.py -c jshdr -i ./data/test/14645_A.png
python infer.py -c jshdr -i ./data/test/14287_A.png
python infer.py -c jshdr -i ./data/test/14708_A.png
python infer.py -c jshdr -i ./data/test/14165_A.png
python infer.py -c jshdr -i ./data/test/14551_A.png
python infer.py -c jshdr -i ./data/test/14341_A.png
python infer.py -c jshdr -i ./data/test/14677_A.png
python infer.py -c jshdr -i ./data/test/14285_A.png
python infer.py -c jshdr -i ./data/test/14334_A.png
python infer.py -c jshdr -i ./data/test/14227_A.png
python infer.py -c jshdr -i ./data/test/14087_A.png
python infer.py -c jshdr -i ./data/test/14441_A.png
python infer.py -c jshdr -i ./data/test/14322_A.png
python infer.py -c jshdr -i ./data/test/14426_A.png
python infer.py -c jshdr -i ./data/test/14745_A.png
python infer.py -c jshdr -i ./data/test/14500_A.png
python infer.py -c jshdr -i ./data/test/14051_A.png
python infer.py -c jshdr -i ./data/test/14922_A.png
python infer.py -c jshdr -i ./data/test/14043_A.png
python infer.py -c jshdr -i ./data/test/14994_A.png
python infer.py -c jshdr -i ./data/test/14525_A.png
python infer.py -c jshdr -i ./data/test/14889_A.png
python infer.py -c jshdr -i ./data/test/14969_A.png
python infer.py -c jshdr -i ./data/test/14386_A.png
python infer.py -c jshdr -i ./data/test/14557_A.png
python infer.py -c jshdr -i ./data/test/14773_A.png
python infer.py -c jshdr -i ./data/test/14501_A.png
python infer.py -c jshdr -i ./data/test/14343_A.png
python infer.py -c jshdr -i ./data/test/14916_A.png
python infer.py -c jshdr -i ./data/test/14310_A.png
python infer.py -c jshdr -i ./data/test/14535_A.png
python infer.py -c jshdr -i ./data/test/14950_A.png
python infer.py -c jshdr -i ./data/test/14710_A.png
python infer.py -c jshdr -i ./data/test/14949_A.png
python infer.py -c jshdr -i ./data/test/14619_A.png
python infer.py -c jshdr -i ./data/test/14362_A.png
python infer.py -c jshdr -i ./data/test/14066_A.png
python infer.py -c jshdr -i ./data/test/14369_A.png
python infer.py -c jshdr -i ./data/test/14074_A.png
python infer.py -c jshdr -i ./data/test/14731_A.png
python infer.py -c jshdr -i ./data/test/14529_A.png
python infer.py -c jshdr -i ./data/test/14564_A.png
python infer.py -c jshdr -i ./data/test/14944_A.png
python infer.py -c jshdr -i ./data/test/14775_A.png
python infer.py -c jshdr -i ./data/test/14344_A.png
python infer.py -c jshdr -i ./data/test/14211_A.png
python infer.py -c jshdr -i ./data/test/14296_A.png
python infer.py -c jshdr -i ./data/test/14299_A.png
python infer.py -c jshdr -i ./data/test/14635_A.png
python infer.py -c jshdr -i ./data/test/14268_A.png
python infer.py -c jshdr -i ./data/test/14220_A.png
python infer.py -c jshdr -i ./data/test/14286_A.png
python infer.py -c jshdr -i ./data/test/14006_A.png
python infer.py -c jshdr -i ./data/test/14486_A.png
python infer.py -c jshdr -i ./data/test/14580_A.png
python infer.py -c jshdr -i ./data/test/14142_A.png
python infer.py -c jshdr -i ./data/test/14470_A.png
python infer.py -c jshdr -i ./data/test/14980_A.png
python infer.py -c jshdr -i ./data/test/14313_A.png
python infer.py -c jshdr -i ./data/test/14357_A.png
python infer.py -c jshdr -i ./data/test/14914_A.png
python infer.py -c jshdr -i ./data/test/14859_A.png
python infer.py -c jshdr -i ./data/test/14890_A.png
python infer.py -c jshdr -i ./data/test/14591_A.png
python infer.py -c jshdr -i ./data/test/14681_A.png
python infer.py -c jshdr -i ./data/test/14828_A.png
python infer.py -c jshdr -i ./data/test/14228_A.png
python infer.py -c jshdr -i ./data/test/14118_A.png
python infer.py -c jshdr -i ./data/test/14810_A.png
python infer.py -c jshdr -i ./data/test/14266_A.png
python infer.py -c jshdr -i ./data/test/14789_A.png
python infer.py -c jshdr -i ./data/test/14981_A.png
python infer.py -c jshdr -i ./data/test/14832_A.png
python infer.py -c jshdr -i ./data/test/14358_A.png
python infer.py -c jshdr -i ./data/test/14276_A.png
python infer.py -c jshdr -i ./data/test/14307_A.png
python infer.py -c jshdr -i ./data/test/14401_A.png
python infer.py -c jshdr -i ./data/test/14255_A.png
python infer.py -c jshdr -i ./data/test/14844_A.png
python infer.py -c jshdr -i ./data/test/14355_A.png
python infer.py -c jshdr -i ./data/test/14012_A.png
python infer.py -c jshdr -i ./data/test/14002_A.png
python infer.py -c jshdr -i ./data/test/14829_A.png
python infer.py -c jshdr -i ./data/test/14192_A.png
python infer.py -c jshdr -i ./data/test/14569_A.png
python infer.py -c jshdr -i ./data/test/14271_A.png
python infer.py -c jshdr -i ./data/test/14595_A.png
python infer.py -c jshdr -i ./data/test/14082_A.png
python infer.py -c jshdr -i ./data/test/14069_A.png
python infer.py -c jshdr -i ./data/test/14278_A.png
python infer.py -c jshdr -i ./data/test/14538_A.png
python infer.py -c jshdr -i ./data/test/14176_A.png
python infer.py -c jshdr -i ./data/test/14371_A.png
python infer.py -c jshdr -i ./data/test/14626_A.png
python infer.py -c jshdr -i ./data/test/14512_A.png
python infer.py -c jshdr -i ./data/test/14101_A.png
python infer.py -c jshdr -i ./data/test/14072_A.png
python infer.py -c jshdr -i ./data/test/14324_A.png
python infer.py -c jshdr -i ./data/test/14629_A.png
python infer.py -c jshdr -i ./data/test/14976_A.png
python infer.py -c jshdr -i ./data/test/14233_A.png
python infer.py -c jshdr -i ./data/test/14547_A.png
python infer.py -c jshdr -i ./data/test/14078_A.png
python infer.py -c jshdr -i ./data/test/14698_A.png
python infer.py -c jshdr -i ./data/test/14915_A.png
python infer.py -c jshdr -i ./data/test/14263_A.png
python infer.py -c jshdr -i ./data/test/14457_A.png
python infer.py -c jshdr -i ./data/test/14772_A.png
python infer.py -c jshdr -i ./data/test/14518_A.png
python infer.py -c jshdr -i ./data/test/14738_A.png
python infer.py -c jshdr -i ./data/test/14788_A.png
python infer.py -c jshdr -i ./data/test/14692_A.png
python infer.py -c jshdr -i ./data/test/14308_A.png
python infer.py -c jshdr -i ./data/test/14919_A.png
python infer.py -c jshdr -i ./data/test/14955_A.png
python infer.py -c jshdr -i ./data/test/14258_A.png
python infer.py -c jshdr -i ./data/test/14163_A.png
python infer.py -c jshdr -i ./data/test/14028_A.png
python infer.py -c jshdr -i ./data/test/14172_A.png
python infer.py -c jshdr -i ./data/test/14737_A.png
python infer.py -c jshdr -i ./data/test/14837_A.png
python infer.py -c jshdr -i ./data/test/14487_A.png
python infer.py -c jshdr -i ./data/test/14761_A.png
python infer.py -c jshdr -i ./data/test/14925_A.png
python infer.py -c jshdr -i ./data/test/14041_A.png
python infer.py -c jshdr -i ./data/test/14242_A.png
python infer.py -c jshdr -i ./data/test/14640_A.png
python infer.py -c jshdr -i ./data/test/14600_A.png
python infer.py -c jshdr -i ./data/test/14462_A.png
python infer.py -c jshdr -i ./data/test/14790_A.png
python infer.py -c jshdr -i ./data/test/14988_A.png
python infer.py -c jshdr -i ./data/test/14633_A.png
python infer.py -c jshdr -i ./data/test/14485_A.png
python infer.py -c jshdr -i ./data/test/14011_A.png
python infer.py -c jshdr -i ./data/test/14897_A.png
python infer.py -c jshdr -i ./data/test/14911_A.png
python infer.py -c jshdr -i ./data/test/14923_A.png
python infer.py -c jshdr -i ./data/test/14696_A.png
python infer.py -c jshdr -i ./data/test/14599_A.png
python infer.py -c jshdr -i ./data/test/14744_A.png
python infer.py -c jshdr -i ./data/test/14270_A.png
python infer.py -c jshdr -i ./data/test/14520_A.png
python infer.py -c jshdr -i ./data/test/14279_A.png
python infer.py -c jshdr -i ./data/test/14239_A.png
python infer.py -c jshdr -i ./data/test/14793_A.png
python infer.py -c jshdr -i ./data/test/14056_A.png
python infer.py -c jshdr -i ./data/test/14656_A.png
python infer.py -c jshdr -i ./data/test/14879_A.png
python infer.py -c jshdr -i ./data/test/14849_A.png
python infer.py -c jshdr -i ./data/test/14515_A.png
python infer.py -c jshdr -i ./data/test/14730_A.png
python infer.py -c jshdr -i ./data/test/14715_A.png
python infer.py -c jshdr -i ./data/test/14391_A.png
python infer.py -c jshdr -i ./data/test/14998_A.png
python infer.py -c jshdr -i ./data/test/14173_A.png
python infer.py -c jshdr -i ./data/test/14742_A.png
python infer.py -c jshdr -i ./data/test/14854_A.png
python infer.py -c jshdr -i ./data/test/14697_A.png
python infer.py -c jshdr -i ./data/test/14015_A.png
python infer.py -c jshdr -i ./data/test/14079_A.png
python infer.py -c jshdr -i ./data/test/14247_A.png
python infer.py -c jshdr -i ./data/test/14123_A.png
python infer.py -c jshdr -i ./data/test/14802_A.png
python infer.py -c jshdr -i ./data/test/14065_A.png
python infer.py -c jshdr -i ./data/test/14016_A.png
python infer.py -c jshdr -i ./data/test/14197_A.png
python infer.py -c jshdr -i ./data/test/14904_A.png
python infer.py -c jshdr -i ./data/test/14838_A.png
python infer.py -c jshdr -i ./data/test/14155_A.png
python infer.py -c jshdr -i ./data/test/14653_A.png
python infer.py -c jshdr -i ./data/test/14036_A.png
python infer.py -c jshdr -i ./data/test/14601_A.png
python infer.py -c jshdr -i ./data/test/14416_A.png
python infer.py -c jshdr -i ./data/test/14657_A.png
python infer.py -c jshdr -i ./data/test/14893_A.png
python infer.py -c jshdr -i ./data/test/14184_A.png
python infer.py -c jshdr -i ./data/test/14555_A.png
python infer.py -c jshdr -i ./data/test/14297_A.png
python infer.py -c jshdr -i ./data/test/14682_A.png
python infer.py -c jshdr -i ./data/test/14997_A.png
python infer.py -c jshdr -i ./data/test/14510_A.png
python infer.py -c jshdr -i ./data/test/14400_A.png
python infer.py -c jshdr -i ./data/test/14273_A.png
python infer.py -c jshdr -i ./data/test/14823_A.png
python infer.py -c jshdr -i ./data/test/14496_A.png
python infer.py -c jshdr -i ./data/test/14758_A.png
python infer.py -c jshdr -i ./data/test/14689_A.png
python infer.py -c jshdr -i ./data/test/14766_A.png
python infer.py -c jshdr -i ./data/test/14693_A.png
python infer.py -c jshdr -i ./data/test/14194_A.png
python infer.py -c jshdr -i ./data/test/14218_A.png
python infer.py -c jshdr -i ./data/test/14954_A.png
python infer.py -c jshdr -i ./data/test/14651_A.png
python infer.py -c jshdr -i ./data/test/14499_A.png
python infer.py -c jshdr -i ./data/test/14193_A.png
python infer.py -c jshdr -i ./data/test/14957_A.png
python infer.py -c jshdr -i ./data/test/14127_A.png
python infer.py -c jshdr -i ./data/test/14045_A.png
python infer.py -c jshdr -i ./data/test/14885_A.png
python infer.py -c jshdr -i ./data/test/14398_A.png
python infer.py -c jshdr -i ./data/test/14960_A.png
python infer.py -c jshdr -i ./data/test/14603_A.png
python infer.py -c jshdr -i ./data/test/14724_A.png
python infer.py -c jshdr -i ./data/test/14020_A.png
python infer.py -c jshdr -i ./data/test/14393_A.png
python infer.py -c jshdr -i ./data/test/14458_A.png
python infer.py -c jshdr -i ./data/test/14536_A.png
python infer.py -c jshdr -i ./data/test/14571_A.png
python infer.py -c jshdr -i ./data/test/14480_A.png
python infer.py -c jshdr -i ./data/test/14533_A.png
python infer.py -c jshdr -i ./data/test/14576_A.png
python infer.py -c jshdr -i ./data/test/14720_A.png
python infer.py -c jshdr -i ./data/test/14005_A.png
python infer.py -c jshdr -i ./data/test/14637_A.png
python infer.py -c jshdr -i ./data/test/14780_A.png
python infer.py -c jshdr -i ./data/test/14209_A.png
python infer.py -c jshdr -i ./data/test/14891_A.png
python infer.py -c jshdr -i ./data/test/14182_A.png
python infer.py -c jshdr -i ./data/test/14690_A.png
python infer.py -c jshdr -i ./data/test/14562_A.png
python infer.py -c jshdr -i ./data/test/14506_A.png
python infer.py -c jshdr -i ./data/test/14423_A.png
python infer.py -c jshdr -i ./data/test/14996_A.png
python infer.py -c jshdr -i ./data/test/14507_A.png
python infer.py -c jshdr -i ./data/test/14440_A.png
python infer.py -c jshdr -i ./data/test/14970_A.png
python infer.py -c jshdr -i ./data/test/14846_A.png
python infer.py -c jshdr -i ./data/test/14189_A.png
python infer.py -c jshdr -i ./data/test/14128_A.png
python infer.py -c jshdr -i ./data/test/14122_A.png
python infer.py -c jshdr -i ./data/test/14474_A.png
python infer.py -c jshdr -i ./data/test/14868_A.png
python infer.py -c jshdr -i ./data/test/14178_A.png
python infer.py -c jshdr -i ./data/test/14556_A.png
python infer.py -c jshdr -i ./data/test/14866_A.png
python infer.py -c jshdr -i ./data/test/14906_A.png
